### ISSUE TITLE
能识别到鱼上钩的动画吗?

### ISSUE THREAD

**Issue by daofeng2015** [babalae/genshin-auto-fish#2]
当上钩的时候,右下角会出现不一样的动画

**Comment by huiyadanli** [comment]
可以的，自动提杆已经准备做了

**Comment by huiyadanli** [comment]
做了个简陋版本的上钩自动提竿，有一定误判率。可以开关这个功能。

https://github.com/babalae/genshin-auto-fish/releases/tag/1.1
