### ISSUE TITLE
请求支持国际版

### ISSUE THREAD

**Issue by oniLand** [babalae/genshin-auto-fish#3]
国际版的进程名为 GenshinImpact.exe

**Comment by oniLand** [comment]
![image](https://user-images.githubusercontent.com/21368333/132690065-1a5b1962-112e-433e-a8c2-aac8e453e186.png)

**Comment by huiyadanli** [comment]
改好了，你试试。

这边下载：https://github.com/babalae/genshin-auto-fish/actions/runs/1217685663

**Comment by oniLand** [comment]
感谢，测试可以使用。
