### ISSUE TITLE
可以把钓鱼框信息写出到本地配置文件吗

### ISSUE THREAD

**Issue by ld1856** [babalae/genshin-auto-fish#4]
目前我这边是每次启动都要重新拖动一下窗口的大小，位置，可以写配置文件下次启动直接读取初始值吗

**Comment by ld1856** [comment]
好像不移动文件夹是可以保存，移动文件夹以后需要重新拖动，不好意思。感谢大佬开源～

**Comment by huiyadanli** [comment]
这个功能已经有了，会自动保存上次的位置的。移动软件后可能不行。。。

**Comment by ld1856** [comment]
是的，现在这样已经很棒了，大佬有空把自动提杆的打个包发出来呗，本地没c#的开发环境

**Comment by ld1856** [comment]
刚刚看到redme更新了，不好意思，不好意思。感谢！！！

**Comment by huiyadanli** [comment]
刚刚在更新，可以从action中获取最新编译版
