### ISSUE TITLE
2k屏幕下不会自动提竿

### ISSUE THREAD

**Issue by FlashKiana** [babalae/genshin-auto-fish#5]
![image](https://user-images.githubusercontent.com/24948734/132951629-afba9098-554e-426d-8007-a9807f365d5a.png)
如图打开了自动提竿，但并没自动提竿记录。

**Comment by huiyadanli** [comment]
把识别区域的上边缘稍微拉高点试试？

**Comment by huiyadanli** [comment]
可以勾选下 显示识别窗口(Debug) 这一项，看看 自动提竿识别窗口 的内容，截图发下。

**Comment by FlashKiana** [comment]
谢谢，框框拉大了确实可以了，我还以为框的越小越精准。
